### PR TITLE
Path fix

### PR DESCRIPTION
**Pull request by knkrth**

### CODE REVIEW

**Comment by 3s3s** [comment]
this not worked for me

**Comment by knkrth** [comment]
Does the opentrade automatically create `sqlite.db` on `opentrade/server/database`? On fresh install it did not create `sqlite.db` on  `opentrade/server/database` I have to manually create `sqlite.db` on  `opentrade/server/database`

**Comment by 3s3s** [comment]
The file sqlite.db should creating automatically by OpenTrade script. But the folder opentrade/server/database should creating with "git clone "

**Comment by knkrth** [comment]
Ok

**Pull request closed without merging**
