### PR TITLE
Need Help To Add  OAuth 2.0 & Mail API

### PR DESCRIPTION
**Pull request by knkrth**
Need help to add sendgrid/ mailgun api & OAuth 2.0 Some of the function does not work correctly. Try to fix it before merging it.

### CODE REVIEW

**Comment by meebovn** [comment]
install @sendgrid/mail

After that you can use sendgrid mail via API in **server/mailer.js**

Example: 

```
const sgMail = require('@sendgrid/mail');
sgMail.setApiKey('**API_KEY**');
        const msg = {
            to: unescape(email),
            from: 'OpenTrade Mailer <'+g_constants.NOREPLY_EMAIL+'>',
            subject: subject,
            html: body
          };
        sgMail.send(msg,   (err, reply) => {...})
```

**Comment by TheRealHotSwap** [comment]
@knkrth did you get this working properly?

**Comment by knkrth** [comment]
@TheRealHotSwap No I did not. Need some adjustment to make it work.

**Comment by Tr0j4n9** [comment]
Please create an issue for this. Not a pull request.

**Pull request closed without merging**
